const data = {
  dates: { maximum: "2022-05-01", minimum: "2022-04-16" },
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/egoyMDLqCxzjnSrWOz50uLlJWmD.jpg",
      genre_ids: [28, 878, 35, 10751],
      id: 675353,
      original_language: "en",
      original_title: "Sonic the Hedgehog 2",
      overview:
        "After settling in Green Hills, Sonic is eager to prove he has what it takes to be a true hero. His test comes when Dr. Robotnik returns, this time with a new partner, Knuckles, in search for an emerald that has the power to destroy civilizations. Sonic teams up with his own sidekick, Tails, and together they embark on a globe-trotting journey to find the emerald before it falls into the wrong hands.",
      popularity: 8640.583,
      poster_path: "/6DrHO1jr3qVrViUO6s6kFiAGM7.jpg",
      release_date: "2022-03-30",
      title: "Sonic the Hedgehog 2",
      video: false,
      vote_average: 7.7,
      vote_count: 249,
    },
    {
      adult: false,
      backdrop_path: "/tj4lzGgHrfjnjVqAKkLIjFqPSyO.jpg",
      genre_ids: [28, 878, 14],
      id: 526896,
      original_language: "en",
      original_title: "Morbius",
      overview:
        "Dangerously ill with a rare blood disorder, and determined to save others suffering his same fate, Dr. Michael Morbius attempts a desperate gamble. What at first appears to be a radical success soon reveals itself to be a remedy potentially worse than the disease.",
      popularity: 1493.306,
      poster_path: "/7gmOjg7lQXGLW8wX31ry1IdIY07.jpg",
      release_date: "2022-03-30",
      title: "Morbius",
      video: false,
      vote_average: 5.8,
      vote_count: 349,
    },
    {
      adult: false,
      backdrop_path: "/yzH5zvuEzzsHLZnn0jwYoPf0CMT.jpg",
      genre_ids: [53, 28],
      id: 760926,
      original_language: "en",
      original_title: "Gold",
      overview:
        "In the not-too-distant future, two drifters traveling through the desert stumble across the biggest gold nugget ever found and the dream of immense wealth and greed takes hold. They hatch a plan to excavate their bounty, with one man leaving to secure the necessary tools while the other remains with the gold. The man who remains must endure harsh desert elements, ravenous wild dogs, and mysterious intruders, while battling the sinking suspicion that he has been abandoned to his fate.",
      popularity: 1453.76,
      poster_path: "/ejXBuNLvK4kZ7YcqeKqUWnCxdJq.jpg",
      release_date: "2022-01-13",
      title: "Gold",
      video: false,
      vote_average: 6.6,
      vote_count: 169,
    },
    {
      adult: false,
      backdrop_path: "/fEe5fe82qHzjO4yej0o79etqsWV.jpg",
      genre_ids: [16, 35, 28, 10751, 80],
      id: 629542,
      original_language: "en",
      original_title: "The Bad Guys",
      overview:
        "When the infamous Bad Guys are finally caught after years of countless heists and being the world’s most-wanted villains, Mr. Wolf brokers a deal to save them all from prison.",
      popularity: 800.402,
      poster_path: "/7qop80YfuO0BwJa1uXk1DXUUEwv.jpg",
      release_date: "2022-03-17",
      title: "The Bad Guys",
      video: false,
      vote_average: 7.7,
      vote_count: 62,
    },
    {
      adult: false,
      backdrop_path: "/wdjdHBDwmynWUrJcNzS24uegvK5.jpg",
      genre_ids: [14, 12],
      id: 338953,
      original_language: "en",
      original_title: "Fantastic Beasts: The Secrets of Dumbledore",
      overview:
        "In an effort to thwart Grindelwald's plans of raising pure-blood wizards to rule over all non-magical beings, Albus Dumbledore enlists his former student Newt Scamander, who agrees to help, though he's unaware of the dangers that lie ahead. Lines are drawn as love and loyalty are tested, even among the truest friends and family, in an increasingly divided wizarding world.",
      popularity: 732.276,
      poster_path: "/jrgifaYeUtTnaH7NF5Drkgjg2MB.jpg",
      release_date: "2022-04-07",
      title: "Fantastic Beasts: The Secrets of Dumbledore",
      video: false,
      vote_average: 7.4,
      vote_count: 50,
    },
    {
      adult: false,
      backdrop_path: "/geYUecpFI2AonDLhjyK9zoVFcMv.jpg",
      genre_ids: [16, 28, 12, 9648],
      id: 810693,
      original_language: "ja",
      original_title: "劇場版 呪術廻戦 0",
      overview:
        "Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won't leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?",
      popularity: 636.106,
      poster_path: "/3pTwMUEavTzVOh6yLN0aEwR7uSy.jpg",
      release_date: "2021-12-24",
      title: "Jujutsu Kaisen 0",
      video: false,
      vote_average: 7.8,
      vote_count: 93,
    },
    {
      adult: false,
      backdrop_path: "/9bbxqz1iPEfZN9Xi2ZjJhkp5JRo.jpg",
      genre_ids: [16, 878, 28],
      id: 610150,
      original_language: "ja",
      original_title: "ドラゴンボール超：スーパーヒーロー",
      overview:
        "The Red Ribbon Army, an evil organization that was once destroyed by Goku in the past, has been reformed by a group of people who have created new and mightier Androids, Gamma 1 and Gamma 2, and seek vengeance against Goku and his family.",
      popularity: 363.669,
      poster_path: "/wFYXVMKWLAoazjWTBNQ4IiQSKJg.jpg",
      release_date: "2022-04-22",
      title: "Dragon Ball Super: Super Hero",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [35],
      id: 671318,
      original_language: "es",
      original_title: "¿Y cómo es él?",
      overview:
        "Thomas is a meek man on the verge of a nervous breakdown. Despite his situation he decides to fake a work trip to go to Vallarta to confront Jero, a taxi driver who is sleeping with his wife.",
      popularity: 362.643,
      poster_path: "/wRMNOaEpFftdQD73G0TaKXFJP3.jpg",
      release_date: "2022-04-07",
      title: "¿Y cómo es él?",
      video: false,
      vote_average: 0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/hw7foD5in5YCs7qY3Pap9pdc1Vc.jpg",
      genre_ids: [28, 12, 35, 10749],
      id: 752623,
      original_language: "en",
      original_title: "The Lost City",
      overview:
        "Follows a reclusive romance novelist who was sure nothing could be worse than getting stuck on a book tour with her cover model, until a kidnapping attempt sweeps them both into a cutthroat jungle adventure, proving life can be so much stranger, and more romantic, than any of her paperback fictions.",
      popularity: 312.417,
      poster_path: "/rnheO8cFvCYcmZsDrBoabJbKLFE.jpg",
      release_date: "2022-03-24",
      title: "The Lost City",
      video: false,
      vote_average: 7.3,
      vote_count: 65,
    },
    {
      adult: false,
      backdrop_path: "/kHd4rwdRtJXnYMraQSrlgPSCsIt.jpg",
      genre_ids: [28, 53],
      id: 628900,
      original_language: "en",
      original_title: "The Contractor",
      overview:
        "After being involuntarily discharged from the U.S. Special Forces, James Harper decides to support his family by joining a private contracting organization alongside his best friend and under the command of a fellow veteran. Overseas on a covert mission, Harper must evade those trying to kill him while making his way back home.",
      popularity: 165.84,
      poster_path: "/rJPGPZ5soaG27MK90oKpioSiJE2.jpg",
      release_date: "2022-03-10",
      title: "The Contractor",
      video: false,
      vote_average: 6.2,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: "/uHmvk8FnoxpgujDU0RIXLkv2fNt.jpg",
      genre_ids: [16, 35],
      id: 573164,
      original_language: "es",
      original_title: "Un rescate de huevitos",
      overview:
        "Toto and his friends must rescue his egg children after they're taken away for a gourmet food event in Africa.",
      popularity: 238.2,
      poster_path: "/ewrIYKTLaqerwznGzNhmqr0huTs.jpg",
      release_date: "2021-08-12",
      title: "An Egg Rescue",
      video: false,
      vote_average: 8.1,
      vote_count: 298,
    },
    {
      adult: false,
      backdrop_path: "/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg",
      genre_ids: [27, 53, 12, 9648],
      id: 522444,
      original_language: "en",
      original_title: "Black Water: Abyss",
      overview:
        "An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.",
      popularity: 211.598,
      poster_path: "/pmAv14TPE2vKMIRrVeCd1Ll7K94.jpg",
      release_date: "2020-07-09",
      title: "Black Water: Abyss",
      video: false,
      vote_average: 5.1,
      vote_count: 315,
    },
    {
      adult: false,
      backdrop_path: "/fMiEp00v8gGWEceL4QeLu6H6z69.jpg",
      genre_ids: [28, 12, 18, 14],
      id: 639933,
      original_language: "en",
      original_title: "The Northman",
      overview:
        "Prince Amleth is on the verge of becoming a man when his father is brutally murdered by his uncle, who kidnaps the boy's mother. Two decades later, Amleth is now a Viking who's on a mission to save his mother, kill his uncle and avenge his father.",
      popularity: 173.441,
      poster_path: "/zhLKlUaF1SEpO58ppHIAyENkwgw.jpg",
      release_date: "2022-04-08",
      title: "The Northman",
      video: false,
      vote_average: 8,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: "/vo9MRyCMBAdSqZgkI70AfVg8ISI.jpg",
      genre_ids: [12, 10751, 18],
      id: 754067,
      original_language: "fr",
      original_title: "Mystère",
      overview:
        'Stéphane decides to move to the beautiful mountains of Cantal in order to reconnect with his 8-year-old daughter, Victoria, who has been silent since her mother\'s disappearance. During a walk in the forest, a shepherd gives Victoria a puppy named "Mystery" who will gradually give her a taste for life. But very quickly, Stéphane discovers that the animal is in reality a wolf… Despite the warnings and the danger of this situation, he cannot bring himself to separate his daughter from this seemingly harmless ball of hair.',
      popularity: 152.72,
      poster_path: "/u6fBXfWU7jaG0zWYiOvh1myEQC.jpg",
      release_date: "2021-12-15",
      title: "Vicky and Her Mystery",
      video: false,
      vote_average: 7.3,
      vote_count: 329,
    },
    {
      adult: false,
      backdrop_path: "/t5dcjL0ZvHjpcVVXhcMG9I5N0D2.jpg",
      genre_ids: [10402, 16],
      id: 554594,
      original_language: "en",
      original_title: "Koati",
      overview:
        "A coati, a butterfly and a frog join forces in order to avoid an evil snake that is destroying their homes.",
      popularity: 137.371,
      poster_path: "/uTHtqB6fqchXVWQO8kKZ2F7ScXy.jpg",
      release_date: "2021-10-22",
      title: "Koati",
      video: false,
      vote_average: 7.5,
      vote_count: 54,
    },
    {
      adult: false,
      backdrop_path: "/ffsEyx9TfP8oOeNgTetgDUgndYw.jpg",
      genre_ids: [18, 35],
      id: 626735,
      original_language: "en",
      original_title: "Dog",
      overview:
        "An army ranger and his dog embark on a road trip along the Pacific Coast Highway to attend a friend's funeral.",
      popularity: 141.029,
      poster_path: "/zHQy4h36WwuCetKS7C3wcT1hkgA.jpg",
      release_date: "2022-02-17",
      title: "Dog",
      video: false,
      vote_average: 7.5,
      vote_count: 197,
    },
    {
      adult: false,
      backdrop_path: "/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg",
      genre_ids: [28, 12, 878, 35, 14],
      id: 545611,
      original_language: "en",
      original_title: "Everything Everywhere All at Once",
      overview:
        "When an interdimensional rupture unravels reality, an unlikely hero must channel her newfound powers to fight bewildering dangers from the multiverse, as the fate of everything hangs in the balance.",
      popularity: 114.675,
      poster_path: "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
      release_date: "2022-03-24",
      title: "Everything Everywhere All at Once",
      video: false,
      vote_average: 8.6,
      vote_count: 22,
    },
    {
      adult: false,
      backdrop_path: "/xGW2hWSmL92qKsgUQEpzTOdWmmk.jpg",
      genre_ids: [12, 28, 878],
      id: 571468,
      original_language: "it",
      original_title: "Freaks Out",
      overview:
        "Four circus freaks with superpowers find themselves trapped in Nazi-occupied Rome after their owner and father figure goes missing in the aftermath of the 1943 surrender of Italy to the Allies.",
      popularity: 32.897,
      poster_path: "/1TkkTo8UiRl5lWM5qkAISHXg0fU.jpg",
      release_date: "2021-10-28",
      title: "Freaks Out",
      video: false,
      vote_average: 7.5,
      vote_count: 459,
    },
    {
      adult: false,
      backdrop_path: "/vivLzGFFDEAg9iXc61g2ogswiRg.jpg",
      genre_ids: [12, 18, 36],
      id: 310119,
      original_language: "en",
      original_title: "Last Days in the Desert",
      overview:
        "On his way out of the wilderness, Jesus struggles with the Devil over the fate of a family in crisis, setting himself up for a dramatic test.",
      popularity: 46.684,
      poster_path: "/7vbP28axycrpchnGSIydUseNkh6.jpg",
      release_date: "2016-05-13",
      title: "Last Days in the Desert",
      video: false,
      vote_average: 5.6,
      vote_count: 127,
    },
    {
      adult: false,
      backdrop_path: "/znpokr30qWVJztgO3t98PVyFLdC.jpg",
      genre_ids: [18, 36, 35],
      id: 617762,
      original_language: "en",
      original_title: "The Electrical Life of Louis Wain",
      overview:
        "The extraordinary true story of eccentric British artist Louis Wain, whose playful, sometimes even psychedelic pictures helped to transform the public's perception of cats forever.",
      popularity: 26.131,
      poster_path: "/zWtI3BI6dnfwRIr7xk2xC84Zian.jpg",
      release_date: "2021-10-21",
      title: "The Electrical Life of Louis Wain",
      video: false,
      vote_average: 7.1,
      vote_count: 208,
    },
  ],
  total_pages: 15,
  total_results: 293,
};

export default data;
